# Generated by Django 3.2.10 on 2023-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=200, null=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
